# Generated by Django 5.2.15 on 2026-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_address_remove_student_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
