import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateReceipt(payment) {

  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(30,64,175);
  doc.text("TuitionFlow",20,20);

  doc.setFontSize(12);
  doc.setTextColor(100);

  doc.text(
    "Payment Receipt",
    20,
    28
  );

  doc.line(20,32,190,32);

  const receiptNumber =
    "TF-" +
    Date.now();

  autoTable(doc,{
    startY:40,

    body:[
      ["Receipt No",receiptNumber],
      ["Student",payment.student_name],
      ["Amount","৳"+payment.amount],
      ["Month",payment.month],
      ["Year",payment.year],
      ["Payment Date",payment.payment_date],
      ["Status","PAID"]
    ]
  });

  doc.setFontSize(10);

  doc.text(
    "Generated by TuitionFlow",
    20,
    150
  );

  doc.save(
    `Receipt-${payment.student_name}.pdf`
  );

}